version: '2'

services:

  cert:
    image: pgarrett/openssl-alpine
    container_name: cert
    volumes:
      - ./certs:/etc/ssl/certs

  ldap:
    image: pgarrett/ldap-alpine
    container_name: ldap
    ports:
      - 636:636
    volumes_from:
     - cert
